---
abstract: 'getting basic stats of a list in one fell swoop'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Swoop
provides:
  Statistics::Swoop:
    file: lib/Statistics/Swoop.pm
    version: 0.02
requires:
  Carp: 0
  Class::Accessor::Lite: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Statistics-Swoop
version: 0.02
